# Generated by Django 5.2 on 2025-04-10 12:43

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to=users.models.profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_picture',
            field=models.ImageField(upload_to=users.models.student_id_upload_path),
        ),
    ]
