# Generated by Django 5.2 on 2025-04-13 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Seller rating between 1 and 5', max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
