# Generated by Django 5.2 on 2025-04-10 12:51

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to=products.models.product_main_image_path, verbose_name='Main Product Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.product_additional_image_path, verbose_name='Product Image'),
        ),
    ]
